host: ''
port: 8317
tls:
  enable: false
  cert: ''
  key: ''
remote-management:
  allow-remote: false
  secret-key: ''
  disable-control-panel: false
auth-dir: ~/.cli-proxy-api
api-keys:
- sk-iflow-proxy
debug: false
commercial-mode: false
logging-to-file: false
logs-max-total-size-mb: 0
error-logs-max-files: 10
usage-statistics-enabled: false
disable-cooling: false
proxy-url: ''
force-model-prefix: false
request-retry: 3
max-retry-interval: 30
quota-exceeded:
  switch-project: true
  switch-preview-model: true
routing:
  strategy: round-robin
ws-auth: false
streaming:
  keepalive-seconds: 15
  bootstrap-retries: 2
nonstream-keepalive-interval: 30
oauth-model-alias: {}
